### PR TITLE
WIP - Implement new layout design

### LINKED ISSUE #13: Create html+css in sbt
We will integrate the new html+css in sbt

### LINKED ISSUE #17: Create theme <code>+<pre>
We will define a list of color to create a theme to show the code in frees.io

### PR DESCRIPTION
**Pull request by israelperezglez**
@raulraja could you review this PR please?

fixed #13 
fixed #17

### CODE REVIEW

**Comment by raulraja** [comment]
Looks good @israelperezglez , I'll use this branch to fix the docs before merging it

**Comment by raulraja** [comment]
Great work :clap:

**Comment by israelperezglez** [comment]
@raulraja perfect ;)

**Comment by juanpedromoreno** [comment]
I'm merging this PR before moving docs to the main freestyle repo. Please, @raulraja could you have a look? Thanks!

**Pull request merged**
